
SELECT * FROM employees;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM STUDENTS;
-- 1. Find the department with the highest average salary.
SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVG(SALARY) DESC
LIMIT 1;


-- 2. Find the department with the lowest average salary.
SELECT DEPARTMENT, AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVG(SALARY) ASC
LIMIT 1;


-- 3. Find the department with the highest total salary.
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY SUM(SALARY) DESC
LIMIT 1;


-- 4. Find the department with the largest number of employees.
SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY COUNT(*) DESC
LIMIT 1;


-- 5. Find the city with the largest number of employees.
SELECT CITY, COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY CITY
ORDER BY COUNT(*) DESC
LIMIT 1;


-- 6. Find the department with the highest average performance score.
SELECT DEPARTMENT, AVG(PERFORMANCE_SCORE) AS AVERAGE_PERFORMANCE
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY AVG(PERFORMANCE_SCORE) DESC
LIMIT 1;


-- 7. Find the student department with the highest average marks.
SELECT DEPARTMENT, AVG(MARKS) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY DEPARTMENT
ORDER BY AVG(MARKS) DESC
LIMIT 1;


-- 8. Find the year with the highest average marks.
SELECT YEAR, AVG(MARKS) AS AVERAGE_MARKS
FROM STUDENTS
GROUP BY YEAR
ORDER BY AVG(MARKS) DESC
LIMIT 1;


-- 9. Find the product category with the highest average price.
SELECT CATEGORY, AVG(PRICE) AS AVERAGE_PRICE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY AVG(PRICE) DESC
LIMIT 1;


-- 10. Find the product category with the largest total stock.
SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY SUM(STOCK) DESC
LIMIT 1;